services:
  - type: web
    name: parete-web
    runtime: docker
    plan: free
    healthCheckPath: /login
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_TIMEZONE
        value: Asia/Jakarta
      - key: APP_NAME
        value: Parete
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: mongodb
      - key: MONGODB_URI
        value: mongodb://127.0.0.1:27017
      - key: MONGODB_DATABASE
        value: db_parete
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: PARETE_AUTH_DISABLED
        value: "true"
